[project]
name = "pri-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "evdev>=1.9.3",
    "ipywidgets>=8.1.8",
    "nemo-toolkit[asr]>=2.7.3",
    "numpy>=2.4.6",
    "openai>=2.48.0",
    "peft>=0.19.1",
    "pydantic>=2.13.4",
    "pynput>=1.8.2",
    "scipy>=1.18.0",
    "sounddevice>=0.5.5",
    "torch>=2.13.0",
    "transformers>=4.57.6",
]
